### ISSUE TITLE
"Invalid API response from Nvidia" when opening EnvyUpdate

### ISSUE THREAD

**Issue by sfaria** [fyr77/EnvyUpdate#31] opened 2023-03-29 13:33 UTC
EnvyUpdate version: 2.17 (latest)
Windows 11 22H2 (22621.1413)
GPU: RTX 4080 Founders Edition

![error_message](https://user-images.githubusercontent.com/298792/228554142-b7ddc521-1b59-44d8-9bc1-66c000bf01ca.png)

Unfortunately, there doesn't seem to be any logging, so I can't really provide any more information.

**Comment by fyr77** [comment] 2023-03-29 21:58
Ah, I think I know what the problem is. Creating some kind of logging here would be smart for future problems, I will include that in the next patch.
I believe your GPU's name actually includes the "Founders Edition" string, so my code fails to detect it properly. Up until now, I just filtered out these suffixes manually, but I think I should rethink my method here. 
Patch is incoming the next few days.

**Comment by sfaria** [comment] 2023-03-30 08:30
Awesome, thanks for the update! if you need any additional information from me to debug just tell me.

**Comment by fyr77** [comment] 2023-04-01 16:19
Alright, I think I fixed it in 7173f2ec5e15f27c49398b7c88e77207e90370b0 and version [2.18](https://github.com/fyr77/EnvyUpdate/releases/tag/2.18). Please test it and see if it works for you. @sfaria

**Comment by sfaria** [comment] 2023-04-01 17:55
I get the same response popup using 2.18. I took a look at your code and did a little digging:

Since I don't really do C# or have an environment, I'm going to hobble around with PowerShell and try to use the same detection method you're using:

```pwshell
$VideoControllers = Get-WmiObject -Query "SELECT * FROM Win32_VideoController"
$VideoControllers.GetPropertyValue("Description")
```

This gives me the value `NVIDIA GeForce RTX 4080`. There doesn't seem to be any reference to "Founder's Edition" in there, unfortunately.

```pwshell
 $VideoControllers.GetPropertyValue("DriverVersion")
```

Gives me `31.0.15.3141`

``pwshell
$OfflineGPUVersion = $VideoControllers.GetPropertyValue("DriverVersion")
$OfflineGPUVersion = $OfflineGpuVersion.Replace(".", "")
$Index = (([array]0,($OfflineGPUVersion.Length-5)) | measure -Maximum).Maximum
$OfflineGPUVersion = $OfflineGPUVersion.Substring($Index)
$OfflineGPUVersion = $OfflineGPUVersion.Substring(0, 3) + "." + $OfflineGPUVersion.Substring(3)
```

Returns `531.41`, which seems sensible so that's working.

GPU Detection seems to work now:

``pwshell
$GPUName = $VideoControllers.GetPropertyValue("VideoProcessor").ToLower()
```

Outputs `nvidia geforce rtx 4080`

``pwshell
$GPUName -match '(geforce )?.tx \w*\d*'
```

Returns True.

Maybe you can use some of this output to figure out what's going on?

**Comment by fyr77** [comment] 2023-04-01 17:57
Hmm, very odd. I'll look into it, thanks for the info.

**Comment by sfaria** [comment] 2023-04-01 17:58
No problem, if you need any info dumps please let me know.

**Comment by fyr77** [comment] 2023-04-01 18:28
@sfaria I made a new build from commit 6a10abc334a1ce10978aef3b3c39c006ef9a11ef, please try this one. It should still throw an error, but a more useful one this time.
https://github.com/fyr77/EnvyUpdate/releases/tag/2.19-pre1

**Comment by sfaria** [comment] 2023-04-01 18:42
Here's what it output: 

![image](https://user-images.githubusercontent.com/298792/229308698-0f11c16f-7859-437b-a2e1-4146191f5196.png)

**Comment by fyr77** [comment] 2023-04-03 16:56
Very strange, it seems that EnvyUpdate cannot properly find your GPU in the Nvidia master list. Could you try opening this URL in a browser? It should give you a massive XML list of graphics cards: https://www.nvidia.com/Download/API/lookupValueSearch.aspx?TypeID=3

**Comment by sfaria** [comment] 2023-04-03 18:41
It resolves, and here is the chunk with both 4080 and 4080 mobile:

```xml
<LookupValue ParentID="127">
<Name>NVIDIA GeForce RTX 4080</Name>
<Value>999</Value>
</LookupValue>
<LookupValue ParentID="127">
</LookupValue>
<LookupValue ParentID="128">
<Name>L4</Name>
<Value>1009</Value>
</LookupValue>
<LookupValue ParentID="128">
<Name>L40</Name>
<Value>1003</Value>
</LookupValue>
<LookupValue ParentID="129">
<Name>GeForce RTX 4090 Laptop GPU</Name>
<Value>1004</Value>
</LookupValue>
<LookupValue ParentID="129">
<Name>GeForce RTX 4080 Laptop GPU</Name>
<Value>1005</Value>
</LookupValue>
```

**Comment by fyr77** [comment] 2023-04-03 19:03
Alright, thank you for checking. Please use [this build](https://github.com/fyr77/EnvyUpdate/releases/tag/2.19-pre3), it should create a log file `envyupdate.log`. Please share the log file here. @sfaria

**Comment by sfaria** [comment] 2023-04-03 19:49
Ran the app once - I've attached the log.

[envyupdate.log](https://github.com/fyr77/EnvyUpdate/files/11141923/envyupdate.log)

**Comment by sfaria** [comment] 2023-05-08 12:09
Did you ever figure out what was wrong?

**Comment by fyr77** [comment] 2023-05-08 12:13
@sfaria Sorry for not keeping you updated, university had me occupied - I was not able to figure out the problem so far. Somewhere the data from your GPU gets lost - or never even read out properly. Could you perhaps contact me via email? Perhaps we could debug the code directly on your machine to figure out where the data gets lost...

**Comment by sfaria** [comment] 2023-05-08 12:15
Hey, no worries! You should concentrate on your exams - I'll pull down the project and do some debugging myself. I'll make a PR once I figure it out.

**Comment by fyr77** [comment] 2023-05-08 12:17
Alright, thank you! That codebase is a bit old and not always completely logical... (I should rewrite a few things probably) - please ask if anything seems off.

**Comment by fyr77** [comment] 2023-07-08 21:19
I have gotten my hands on a GTX 1080 Ti, which seems to have triggered the same issue you were having. I will release 2.19 now, please test that when you have the time. @sfaria

**Comment by sfaria** [comment] 2023-07-09 12:14
Hey! Thanks for looking into this. Sorry I didn't get time to look into the issue myself - I started a new job search shortly after our last update and didn't get the time.

I'll install the latest version and let you know.

**Comment by sfaria** [comment] 2023-07-09 12:16
Same issue: 

![image](https://github.com/fyr77/EnvyUpdate/assets/298792/44db6e0f-c180-4725-888b-49454abd220c)

**Comment by fyr77** [comment] 2023-07-09 12:44
Hmm, very unfortunate. I did fix another issue at least.
I'll keep looking into it.

**Comment by fyr77** [comment] 2023-07-09 16:41
Hi again @sfaria.
I have released another new version with some internal improvements to logic, but I don't expect this to fix the problem. Still, I added a button in the settings to enable logging and improved the log messages, so I would appreciate it if you could share another log file from 2.20.

If it helps in any way, here is one from my current system: 
[envyupdate.log](https://github.com/fyr77/EnvyUpdate/files/11995659/envyupdate.log)

**Comment by sfaria** [comment] 2023-07-10 11:21
Hey @fyr77!

Great work on getting logging in - I enabled it and restarted the program. I've attached the log ouput. Thanks!

[envyupdate.log](https://github.com/fyr77/EnvyUpdate/files/12001292/envyupdate.log)

**Comment by nezorflame** [comment] 2023-08-06 10:45
Got the same error.
RTX 4080 Laptop, version 2.20.
![image](https://github.com/fyr77/EnvyUpdate/assets/3906766/b40382c0-62b6-4fed-8403-653f350ec28b)
![image](https://github.com/fyr77/EnvyUpdate/assets/3906766/2d0f01de-6226-4221-b8ec-b90c27cba147)

**Comment by fyr77** [comment] 2023-08-06 15:28
I may have found the issue. Nvidia switched their titling in the 40 series, from "GeForce RTX 3080" to "NVIDIA GeForce RTX 4080". I believe my code does not account for this. I am currently not home, I will attempt to fix this for the next release and also release a fixed 2.X version by the end of the coming week.

**Comment by nezorflame** [comment] 2023-08-06 20:48
@fyr77 sounds great, feel free to ping me to test it!

**Comment by fyr77** [comment] 2023-08-11 20:44
I have just released 2.21, please test this version. It should fix your issue.

**Comment by nezorflame** [comment] 2023-08-12 01:48
@fyr77 indeed, it works now. Thanks!

**Comment by fyr77** [comment] 2023-08-12 07:38
@nezorflame Wonderful!

@sfaria If possible, please confirm it works for you as well. If yes, I will close the issue.

**Comment by sfaria** [comment] 2023-08-12 12:42
@fyr77 - Working now for me as well. Great work, and thanks for looking into this!

**Closed** 2023-08-12 14:49 UTC
Labels: bug

**Comment by nezorflame** [comment] 2023-08-12 16:58
Just an FYI - for some reason WIndows Defender now considers your new version a trojan: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FBearfoos.A!ml&threatid=2147731250

**Comment by fyr77** [comment] 2023-08-12 17:24
@nezorflame Annoying... Thank you for the heads-up. It is amusing, since I merely changed two lines of code which should have no impact on virus detection. 
Weirdly enough, my own installation of Windows 11 does not recognize it as a virus. As always, Windows Defender is a mystery ;)
